# config.py
NUM_STEPS = 30
NUM_PLAYERS = 4
INITIAL_CASH = 100000

# 4つの銘柄
STOCKS = ['小島電機', '井上パン', '笹田工務店', 'スーパー山田']

IS_RANKING_VISIBLE = True
RANKING_INTERVAL = 5

HUMAN_PLAYER_ID = 'Player_A'
HUMAN_INPUT_MAX_STEPS = 3